# Generated by Django 5.0.7 on 2026-06-22 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='story',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='video',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='shipment',
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
