# Generated by Django 5.0.7 on 2026-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auctionproduct_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='end_time',
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='auction_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
